export const auth_constants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
}

export const user_constants = {
  FOOD_LIST_REQUEST: 'FOOD_LIST_REQUEST',
  FOOD_LIST_SUCCESS: 'FOOD_LIST_SUCCESS',
  FOOD_LIST_FAILURE: 'FOOD_LIST_FAILURE',
}
